<a href="https://colab.research.google.com/github/Cothilyba77/Projet_final_Force_N/blob/main/Exploration%20de%20donn%C3%A9es.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. IMPORTATION DES LIBRAIRIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# importation des données

In [3]:
df_malaria = pd.read_csv('/content/incidence-of-malaria.csv')
df_mortality = pd.read_csv('/content/maternal-mortality.csv')
df_prenatal = pd.read_csv('/content/share-of-mothers-receiving-at-least-one-antenatal-visit-during-pregnancy.csv')

In [ ]:
df_malaria.head(50)

,Entity,Code,Year,Maternal mortality ratio,World region according to OWID,Maternal mortality ratio (Annotations)
0,Afghanistan,AFG,1985,1910.3416,Asia,NaN
1,Afghanistan,AFG,1986,1602.9429,Asia,NaN
2,Afghanistan,AFG,1987,1586.7214,Asia,NaN
3,Afghanistan,AFG,1988,1413.9326,Asia,NaN
4,Afghanistan,AFG,1989,1382.7299,Asia,NaN

In [4]:
df_combined = df_malaria.merge(df_mortality, on=['Entity', 'Year','Code'], how='outer')
df_combined = df_combined.merge(df_prenatal, on=['Entity', 'Year','Code'], how='outer')

In [7]:
df_combined.head(5)

,Entity,Code,Year,"Incidence of malaria (per 1,000 population at risk)",Maternal mortality ratio,World region according to OWID,Maternal mortality ratio (Annotations),Pregnant women receiving prenatal care (%)
0,Afghanistan,AFG,1985,NaN,1910.3416,Asia,NaN,NaN
1,Afghanistan,AFG,1986,NaN,1602.9429,Asia,NaN,NaN
2,Afghanistan,AFG,1987,NaN,1586.7214,Asia,NaN,NaN
3,Afghanistan,AFG,1988,NaN,1413.9326,Asia,NaN,NaN
4,Afghanistan,AFG,1989,NaN,1382.7299,Asia,NaN,NaN

In [ ]:
df_present_entities = df_combined.dropna(subset=['Entity'])
display(df_present_entities.head())

In [8]:
unique_entities = df_combined['Entity'].unique()
display(unique_entities)

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Asia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo', 'Costa Rica', "Cote d'Ivoire", 'Croatia',
       'Cuba', 'Cyprus', 'Czechia', 'Democratic Republic of Congo',
       'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
       'East Asia and Pacific (WB)', 'East Timor', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Europe', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'High-income countries', 'Honduras', 'Hong Kong',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latin America and Caribbean (WB)', 'Latvia',
       'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania',
       'Low-income countries', 'Lower-middle-income countries',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
       'Mayotte', 'Mexico', 'Micronesia (country)',
       'Middle East, North Africa, Afghanistan and Pakistan (WB)',
       'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North America',
       'North Korea', 'North Macedonia', 'Norway', 'Oceania', 'Oman',
       'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South America',
       'South Asia (WB)', 'South Korea', 'South Sudan', 'Spain',
       'Sri Lanka', 'Sub-Saharan Africa (WB)', 'Sudan', 'Suriname',
       'Sweden', 'Switzerland', 'Syria', 'Tajikistan', 'Tanzania',
       'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu',
       'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Upper-middle-income countries', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'World', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

In [9]:
west_african_countries = [
    'Benin',
    'Burkina Faso',
    'Cote d\'Ivoire',
    'Gambia',
    'Ghana',
    'Guinea',
    'Guinea-Bissau',
    'Liberia',
    'Mali',
    'Niger',
    'Nigeria',
    'Senegal',
    'Sierra Leone',
    'Togo'
]

df_westafrica = df_combined[df_combined['Entity'].isin(west_african_countries)]
display(df_westafrica.head())

,Entity,Code,Year,"Incidence of malaria (per 1,000 population at risk)",Maternal mortality ratio,World region according to OWID,Maternal mortality ratio (Annotations),Pregnant women receiving prenatal care (%)
984,Benin,BEN,1985,NaN,718.65410,Africa,NaN,NaN
985,Benin,BEN,1986,NaN,681.50360,Africa,NaN,NaN
986,Benin,BEN,1987,NaN,652.18610,Africa,NaN,NaN
987,Benin,BEN,1988,NaN,633.78674,Africa,NaN,NaN
988,Benin,BEN,1989,NaN,591.92160,Africa,NaN,NaN

In [10]:
df_westafrica.info()

<class 'pandas.core.frame.DataFrame'>
Index: 560 entries, 984 to 8791
Data columns (total 8 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Entity                                               560 non-null    object
 1   Code                                                 560 non-null    object
 2   Year                                                 560 non-null    int64
 3   Incidence of malaria (per 1,000 population at risk)  350 non-null    float64
 4   Maternal mortality ratio                             504 non-null    float64
 5   World region according to OWID                       504 non-null    object
 6   Maternal mortality ratio (Annotations)               0 non-null      object
 7   Pregnant women receiving prenatal care (%)           120 non-null    float64
dtypes: float64(3), int64(1), object(4)
memory usage: 39.4+ KB

In [11]:
df_westafrica.isna().sum()

Entity                                                   0
Code                                                     0
Year                                                     0
Incidence of malaria (per 1,000 population at risk)    210
Maternal mortality ratio                                56
World region according to OWID                          56
Maternal mortality ratio (Annotations)                 560
Pregnant women receiving prenatal care (%)             440
dtype: int64

In [12]:
df_westafrica.head(100)

,Entity,Code,Year,"Incidence of malaria (per 1,000 population at risk)",Maternal mortality ratio,World region according to OWID,Maternal mortality ratio (Annotations),Pregnant women receiving prenatal care (%)
984,Benin,BEN,1985,NaN,718.65410,Africa,NaN,NaN
985,Benin,BEN,1986,NaN,681.50360,Africa,NaN,NaN
986,Benin,BEN,1987,NaN,652.18610,Africa,NaN,NaN
987,Benin,BEN,1988,NaN,633.78674,Africa,NaN,NaN
988,Benin,BEN,1989,NaN,591.92160,Africa,NaN,NaN
...,...,...,...,...,...,...,...,...
1915,Cote d'Ivoire,CIV,2000,490.52,473.46722,Africa,NaN,87.6
1916,Cote d'Ivoire,CIV,2001,502.24,495.45026,Africa,NaN,NaN
1917,Cote d'Ivoire,CIV,2002,506.32,519.81730,Africa,NaN,NaN
1918,Cote d'Ivoire,CIV,2003,509.61,539.48627,Africa,NaN,NaN
1919,Cote d'Ivoire,CIV,2004,500.36,536.08180,Africa,NaN,NaN